=== Svetlozar-Stefanov/FMI/Semester 05 - XML/MovieCollection.dtd
<!ELEMENT MovieCollection (artists, genres, movies)>
<!ELEMENT artists (artist+)>
<!ELEMENT artist (name)>
<!ATTLIST artist id ID #REQUIRED directed IDREFS #IMPLIED acted_in IDREFS #IMPLIED>
<!ELEMENT name (#PCDATA)>

<!ELEMENT genres (genre+)>
<!ELEMENT genre (#PCDATA)>
<!ATTLIST genre id ID #REQUIRED>

<!ELEMENT movies (movie+)>
<!ELEMENT movie (
    title, poster, year, age_restriction,
    length, rating, description, 
    budget, gross_worldwide
    )>
<!ATTLIST movie 
    id ID #REQUIRED
    director IDREF #REQUIRED
    stars IDREFS #REQUIRED
    genres IDREFS #IMPLIED>
<!ELEMENT title (#PCDATA)>
<!ELEMENT poster EMPTY>
<!ATTLIST poster image ENTITY #REQUIRED>
<!ELEMENT year (#PCDATA)>
<!ELEMENT age_restriction (#PCDATA)>
<!ELEMENT length (#PCDATA)>
<!ELEMENT rating (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT budget (#PCDATA)>
<!ELEMENT gross_worldwide (#PCDATA)>

<!NOTATION JPG SYSTEM "image/jpg">
<!ENTITY pulp_fiction SYSTEM "resources/Pulp-Fiction.jpg" NDATA JPG>
<!ENTITY blade_runner SYSTEM "resources/Blade-Runner.jpg" NDATA JPG>
<!ENTITY the_green_mile SYSTEM "resources/The-Green-Mile.jpg" NDATA JPG>
<!ENTITY mr_nobody SYSTEM "resources/Mr-Nobody.jpg" NDATA JPG>
<!ENTITY eternal_sunshine SYSTEM "resources/Eternal-Sunshine.jpg" NDATA JPG>
<!ENTITY oldboy SYSTEM "resources/Oldboy.jpg" NDATA JPG>
<!ENTITY a_clockwork_orange SYSTEM "resources/A-Clockwork-Orange.jpg" NDATA JPG>
<!ENTITY lost_in_translation SYSTEM "resources/Lost-In-Translation.jpg" NDATA JPG>
<!ENTITY interstellar SYSTEM "resources/Interstellar.jpg" NDATA JPG>
<!ENTITY django_unchained SYSTEM "resources/Django-Unchained.jpg" NDATA JPG>

=== Svetlozar-Stefanov/FMI/Semester 05 - XML/MovieCollection.xml
<?xml version="1.0" encoding="UTF-8"?>
 <!DOCTYPE MovieCollection SYSTEM "MovieCollection.dtd">
<?xml-stylesheet type="text/xsl" href="MovieCollection.xsl"?>
<MovieCollection>
    <artists>
        <artist id="A-1" directed="M-PF M-DU" acted_in="M-PF M-DU">
            <name>Quentin Tarantino</name>
        </artist>

        <artist id="A-2" acted_in="M-PF">
            <name>John Travolta</name>
        </artist>

        <artist id="A-3" acted_in="M-PF">
            <name>Uma Thurman</name>
        </artist>

        <artist id="A-4" acted_in="M-PF M-DU">
            <name>Samuel L. Jackson</name>
        </artist>

        <artist id="A-5" directed="M-BR">
            <name>Ridley Scott</name>
        </artist>

        <artist id="A-6" acted_in="M-BR">
            <name>Harrison Ford</name>
        </artist>

        <artist id="A-7" acted_in="M-BR">
            <name>Sean Young</name>
        </artist>

        <artist id="A-8" acted_in="M-BR">
            <name>Rutger Hauer</name>
        </artist>

        <artist id="A-9" directed="M-TGM">
            <name>Frank Darabont</name>
        </artist>

        <artist id="A-10" acted_in="M-TGM">
            <name>Tom Hanks</name>
        </artist>

        <artist id="A-11" acted_in="M-TGM">
            <name>David Morse</name>
        </artist>

        <artist id="A-12" acted_in="M-TGM">
            <name>Michael Clarke Duncan</name>
        </artist>

        <artist id="A-13" directed="M-MN">
            <name>Jaco Van Dormael</name>
        </artist>

        <artist id="A-14" acted_in="M-MN">
            <name>Jared Leto</name>
        </artist>

        <artist id="A-15" acted_in="M-MN">
            <name>Sarah Polley</name>
        </artist>

        <artist id="A-16" acted_in="M-MN">
            <name>Diane Kruger</name>
        </artist>

        <artist id="A-17" directed="M-ESOTSM">
            <name>Michel Gondry</name>
        </artist>

        <artist id="A-18" acted_in="M-ESOTSM">
            <name>Jim Carrey</name>
        </artist>

        <artist id="A-19" acted_in="M-ESOTSM">
            <name>Kate Winslet</name>
        </artist>

        <artist id="A-20" acted_in="M-ESOTSM">
            <name>Tom Wilkinson</name>
        </artist>

        <artist id="A-21" directed="M-OB">
            <name>Park Chan-wook</name>
        </artist>

        <artist id="A-22" acted_in="M-OB">
            <name>Choi Min-sik</name>
        </artist>

        <artist id="A-23" acted_in="M-OB">
            <name>Yoo Ji-tae</name>
        </artist>

        <artist id="A-24" acted_in="M-OB">
            <name>Kang Hye-jeong</name>
        </artist>

        <artist id="A-25" directed="M-ACO">
            <name>Stanley Kubrick</name>
        </artist>

        <artist id="A-26" acted_in="M-ACO">
            <name>Malcolm McDowell</name>
        </artist>

        <artist id="A-27" acted_in="M-ACO">
            <name>Patrick Magee</name>
        </artist>

        <artist id="A-28" acted_in="M-ACO">
            <name>Michael Bates</name>
        </artist>

        <artist id="A-29" directed="M-LIT">
            <name>Sofia Coppola</name>
        </artist>

        <artist id="A-30" acted_in="M-LIT">
            <name>Bill Murray</name>
        </artist>

        <artist id="A-31" acted_in="M-LIT">
            <name>Scarlett Johansson</name>
        </artist>

        <artist id="A-32" acted_in="M-LIT">
            <name>Giovanni Ribisi</name>
        </artist>

        <artist id="A-33" directed="M-I">
            <name>Christopher Nolan</name>
        </artist>

        <artist id="A-34" acted_in="M-I">
            <name>Matthew McConaughey</name>
        </artist>

        <artist id="A-35" acted_in="M-I">
            <name>Anne Hathaway</name>
        </artist>

        <artist id="A-36" acted_in="M-I">
            <name>Jessica Chastain</name>
        </artist>

        <artist id="A-37" acted_in="M-DU">
            <name>Jamie Foxx</name>
        </artist>

        <artist id="A-38" acted_in="M-DU">
            <name>Christoph Waltz</name>
        </artist>

        <artist id="A-39" acted_in="M-DU">
            <name>Leonardo DiCaprio</name>
        </artist>
    </artists>

    <genres>
        <genre id="G-Crime">Crime</genre>
        <genre id="G-Drama">Drama</genre>
        <genre id="G-Action">Action</genre>
        <genre id="G-Sci-Fi">Sci-Fi</genre>
        <genre id="G-Fantasy">Fantasy</genre>
        <genre id="G-Romance">Romance</genre>
        <genre id="G-Western">Western</genre>
        <genre id="G-Mystery">Mystery</genre>
        <genre id="G-Comedy">Comedy</genre>
        <genre id="G-Adventure">Adventure</genre>
    </genres>

    <movies>
        <movie id="M-PF" director="A-1"
            stars="A-2 A-3 A-4 A-1"
            genres="G-Crime G-Drama">
            <title>Pulp Fiction</title>
            <poster image="pulp_fiction"/>
            <year>1994</year>
            <age_restriction>18</age_restriction>
            <length>2h 34m</length>
            <rating>8.9</rating>
            <description>
                The lives of two mob hitmen, a boxer, a gangster and his wife,
                and a pair of diner bandits intertwine in four tales of
                violence and redemption.
            </description>
            <budget>$8,000,000</budget>
            <gross_worldwide>$213,928,762</gross_worldwide>
        </movie>

        <movie id="M-BR" director="A-5"
            stars="A-6 A-7 A-8"
            genres="G-Action G-Drama G-Sci-Fi">
            <title>Blade Runner</title>
            <poster image="blade_runner"/>
            <year>1982</year>
            <age_restriction>AA</age_restriction>
            <length>1h 57m</length>
            <rating>8.1</rating>
            <description>
                A blade runner must pursue and terminate four replicants who stole a
                ship in space and have returned to Earth to find their creator.
            </description>
            <budget>$28,000,000</budget>
            <gross_worldwide>$41,712,525</gross_worldwide>
        </movie>

        <movie id="M-TGM" director="A-9"
            stars="A-10 A-11 A-12"
            genres="G-Crime G-Drama G-Fantasy">
            <title>The Green Mile</title>
            <poster image="the_green_mile"/>
            <year>1999</year>
            <age_restriction>18</age_restriction>
            <length>3h 9m</length>
            <rating>8.6</rating>
            <description>
                A tale set on death row in a Southern jail, where gentle giant John possesses the
                mysterious power to heal people's ailments. When the lead guard, Paul, recognizes
                John's gift, he tries to help stave off the condemned man's execution.
            </description>
            <budget>$60,000,000</budget>
            <gross_worldwide>$286,801,374</gross_worldwide>
        </movie>

        <movie id="M-MN" director="A-13"
            stars="A-14 A-15 A-16"
            genres="G-Drama G-Fantasy G-Romance">
            <title>Mr. Nobody</title>
            <poster image="mr_nobody"/>
            <year>2009</year>
            <age_restriction>15</age_restriction>
            <length>2h 21m</length>
            <rating>7.7</rating>
            <description>
                A boy stands on a station platform as a train is about to leave.
                Should he go with his mother or stay with his father? Infinite possibilities
                arise from this decision. As long as he doesn't choose, anything is possible.
            </description>
            <budget>$47,000,000</budget>
            <gross_worldwide>$3,559,160</gross_worldwide>
        </movie>

        <movie id="M-ESOTSM" director="A-17"
            stars="A-18 A-19 A-20"
            genres="G-Drama G-Romance G-Sci-Fi">
            <title>Eternal Sunshine of the Spotless Mind</title>
            <poster image="eternal_sunshine"/>
            <year>2004</year>
            <age_restriction>15</age_restriction>
            <length>1h 48m</length>
            <rating>8.3</rating>
            <description>
                When their relationship turns sour, a couple undergoes a medical
                procedure to have each other erased from their memories for ever.
            </description>
            <budget>$20,000,000</budget>
            <gross_worldwide>$73,387,734</gross_worldwide>
        </movie>


        <movie id="M-OB" director="A-21"
            stars="A-22 A-23 A-24"
            genres="G-Action G-Drama G-Mystery">
            <title>Oldboy</title>
            <poster image="oldboy"/>
            <year>2003</year>
            <age_restriction>18</age_restriction>
            <length>2h</length>
            <rating>8.4</rating>
            <description>
                After being kidnapped and imprisoned for fifteen years,
                Oh Dae-Su is released, only to find that he must find his captor in five days.
            </description>
            <budget>$3,000,000</budget>
            <gross_worldwide>$17,495,470</gross_worldwide>
        </movie>

        <movie id="M-ACO" director="A-25"
            stars="A-26 A-27 A-28"
            genres="G-Crime G-Sci-Fi">
            <title>A Clockwork Orange</title>
            <poster image="a_clockwork_orange"/>
            <year>1971</year>
            <age_restriction>18</age_restriction>
            <length>2h 16m</length>
            <rating>8.3</rating>
            <description>
                In the future, a sadistic gang leader is imprisoned and volunteers for
                a conduct-aversion experiment, but it doesn't go as planned.
            </description>
            <budget>$2,200,000</budget>
            <gross_worldwide>$26,960,374</gross_worldwide>
        </movie>

        <movie id="M-LIT" director="A-29"
            stars="A-30 A-31 A-32"
            genres="G-Comedy G-Drama">
            <title>Lost in Translation</title>
